<a href="https://colab.research.google.com/github/Shibli-Nomani/project-01--Heart-Disease/blob/main/ANN_under_over_sample_heartdisease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')
import warnings
warnings.filterwarnings("ignore")

Mounted at /content/gdrive

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
path='/content/gdrive/MyDrive/Final Project/train.csv'
df=pd.read_csv(path)
df.head(5)

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,0,-1.422409,0,0,1,-0.366034,-0.460504,0,0,12,5,0,1,4,-0.142328,0,0,0
1,0,-0.653422,0,0,0,-0.366034,-0.460504,0,0,11,5,0,0,2,-1.033281,0,0,1
2,0,0.822955,1,0,0,4.347674,-0.460504,1,0,12,5,2,0,2,1.639578,1,0,0
3,0,-0.208323,0,0,0,-0.366034,-0.460504,0,0,12,5,1,0,1,-1.924234,0,1,0
4,0,2.621233,0,0,0,-0.366034,-0.460504,1,1,9,5,0,1,2,2.530531,0,0,0

In [16]:
from sklearn.model_selection import train_test_split

import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error,confusion_matrix, precision_score, recall_score, f1_score, auc,roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.metrics import mean_absolute_error

import keras
from keras.models import Sequential
from keras.layers import Dense

In [4]:
#target
y=df['HeartDisease']
#features
X=df.copy()
X=df.drop('HeartDisease', axis=1)
X.head(5)

,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,-1.422409,0,0,1,-0.366034,-0.460504,0,0,12,5,0,1,4,-0.142328,0,0,0
1,-0.653422,0,0,0,-0.366034,-0.460504,0,0,11,5,0,0,2,-1.033281,0,0,1
2,0.822955,1,0,0,4.347674,-0.460504,1,0,12,5,2,0,2,1.639578,1,0,0
3,-0.208323,0,0,0,-0.366034,-0.460504,0,0,12,5,1,0,1,-1.924234,0,1,0
4,2.621233,0,0,0,-0.366034,-0.460504,1,1,9,5,0,1,2,2.530531,0,0,0

#**Under Sampling**

In [7]:
df1=df.copy()
#Target
y_us=df1['HeartDisease']
#Features

X_us=df1.copy()
X_us=df1.drop('HeartDisease', axis=1)

In [44]:
from imblearn.under_sampling import NearMiss
NearMiss_obj = NearMiss()
X_us , y_us = NearMiss_obj.fit_resample(X_us,y_us)
print(X_us.shape)
print(y_us.shape)

(31722, 17)
(31722,)

In [45]:
X_us_train, X_us_test, y_us_train, y_us_test = train_test_split(X_us,y_us,test_size = 0.2, random_state=42)

**Multiple Classification Model List**

In [202]:
#to add 1st hidden layer
ml10 = Sequential()
ml10.add(Dense(6,activation = 'relu', input_dim = 17)) #no of feature 17
#to add 2nd hidden layer
ml10.add(Dense(6, activation = 'relu'))
#add output layer as target is in binary formate and reqire 1 neuron
ml10.add(Dense(1, activation = 'sigmoid'))
#compile
ml10.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [203]:
ml10.fit(X_us_train, y_us_train, batch_size = 10, epochs = 50)

Epoch 1/50
2538/2538 [==============================] - 5s 2ms/step - loss: 0.4428 - accuracy: 0.7906
Epoch 2/50
2538/2538 [==============================] - 5s 2ms/step - loss: 0.3472 - accuracy: 0.8501
Epoch 3/50
2538/2538 [==============================] - 6s 2ms/step - loss: 0.3293 - accuracy: 0.8605
Epoch 4/50
2538/2538 [==============================] - 11s 4ms/step - loss: 0.3198 - accuracy: 0.8661
Epoch 5/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.3144 - accuracy: 0.8672
Epoch 6/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.3105 - accuracy: 0.8691
Epoch 7/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.3071 - accuracy: 0.8712
Epoch 8/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.3055 - accuracy: 0.8728
Epoch 9/50
2538/2538 [==============================] - 5s 2ms/step - loss: 0.3044 - accuracy: 0.8743
Epoch 10/50
2538/2538 [==============================] - 5s 2ms/step - loss: 0.3034 - accuracy: 0.8752
Epoch 11/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.3017 - accuracy: 0.8758
Epoch 12/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.3011 - accuracy: 0.8743
Epoch 13/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.3003 - accuracy: 0.8753
Epoch 14/50
2538/2538 [==============================] - 5s 2ms/step - loss: 0.2988 - accuracy: 0.8756
Epoch 15/50
2538/2538 [==============================] - 8s 3ms/step - loss: 0.2985 - accuracy: 0.8761
Epoch 16/50
2538/2538 [==============================] - 5s 2ms/step - loss: 0.2985 - accuracy: 0.8758
Epoch 17/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.2974 - accuracy: 0.8777
Epoch 18/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.2978 - accuracy: 0.8751
Epoch 19/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.2971 - accuracy: 0.8774
Epoch 20/50
2538/2538 [==============================] - 8s 3ms/step - loss: 0.2964 - accuracy: 0.8778
Epoch 21/50
2538/2538 [==============================] - 10s 4ms/step - loss: 0.2962 - accuracy: 0.8786
Epoch 22/50
2538/2538 [==============================] - 8s 3ms/step - loss: 0.2963 - accuracy: 0.8786
Epoch 23/50
2538/2538 [==============================] - 10s 4ms/step - loss: 0.2966 - accuracy: 0.8774
Epoch 24/50
2538/2538 [==============================] - 6s 2ms/step - loss: 0.2965 - accuracy: 0.8791
Epoch 25/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.2953 - accuracy: 0.8800
Epoch 26/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.2946 - accuracy: 0.8789
Epoch 27/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.2947 - accuracy: 0.8803
Epoch 28/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.2942 - accuracy: 0.8789
Epoch 29/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.2948 - accuracy: 0.8790
Epoch 30/50
2538/2538 [==============================] - 5s 2ms/step - loss: 0.2951 - accuracy: 0.8781
Epoch 31/50
2538/2538 [==============================] - 7s 3ms/step - loss: 0.2944 - accuracy: 0.8786
Epoch 32/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.2950 - accuracy: 0.8782
Epoch 33/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.2943 - accuracy: 0.8797
Epoch 34/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.2945 - accuracy: 0.8775
Epoch 35/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.2938 - accuracy: 0.8783
Epoch 36/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.2930 - accuracy: 0.8782
Epoch 37/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.2939 - accuracy: 0.8800
Epoch 38/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.2931 - accuracy: 0.8791
Epoch 39/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.2939 - accuracy: 0.8795
Epoch 40/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.2932 - accuracy: 0.8787
Epoch 41/50
2538/2538 [==============================] - 5s 2ms/step - loss: 0.2930 - accuracy: 0.8806
Epoch 42/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.2934 - accuracy: 0.8803
Epoch 43/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.2927 - accuracy: 0.8805
Epoch 44/50
2538/2538 [==============================] - 5s 2ms/step - loss: 0.2934 - accuracy: 0.8797
Epoch 45/50
2538/2538 [==============================] - 10s 4ms/step - loss: 0.2932 - accuracy: 0.8792
Epoch 46/50
2538/2538 [==============================] - 9s 4ms/step - loss: 0.2927 - accuracy: 0.8801
Epoch 47/50
2538/2538 [==============================] - 6s 2ms/step - loss: 0.2924 - accuracy: 0.8805
Epoch 48/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.2927 - accuracy: 0.8799
Epoch 49/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.2925 - accuracy: 0.8795
Epoch 50/50
2538/2538 [==============================] - 4s 2ms/step - loss: 0.2923 - accuracy: 0.8798

In [204]:
 y_us_pred=ml10.predict(X_us_test)
 y_us_pred[y_us_pred <= 0.5] = 0
 y_us_pred[y_us_pred > 0.5] = 1

In [205]:
fp, tp, tn = roc_curve(y_us_test, y_us_pred)

Train_Accuracy_loss = ml10.evaluate(X_us_train, y_us_train)
Train_Accuracy = (Train_Accuracy_loss[1])
Train_loss = (Train_Accuracy_loss[0])

Test_Accuracy_loss =  ml10.evaluate(X_us_test, y_us_test)
Test_Accuracy = (Test_Accuracy_loss[1])
Test_loss = (Test_Accuracy_loss[0])

Precission = precision_score(y_us_test, y_us_pred)
Recall= recall_score(y_us_test, y_us_pred)
f1_Score=f1_score(y_us_test, y_us_pred)
AUC = auc(fp, tp)
mbe=mean_absolute_error(y_us_test, y_us_pred)
list_name = [["Train Accuracy", Train_Accuracy], ["Train loss", Train_loss], ["Test Accuracy", Test_Accuracy], ["Test loss", Test_loss],
             ["Precision",Precission], ["Recall", Recall],
             ['F1 Score',f1_Score], ["AUC", AUC],["mean abs error",mbe]]
model_columns = pd.DataFrame (list_name, columns = ['measures', 'values'])
model_columns

794/794 [==============================] - 1s 1ms/step - loss: 0.2909 - accuracy: 0.8810
199/199 [==============================] - 0s 1ms/step - loss: 0.2982 - accuracy: 0.8783

         measures    values
0  Train Accuracy  0.881034
1      Train loss  0.290853
2   Test Accuracy  0.878329
3       Test loss  0.298178
4       Precision  0.940933
5          Recall  0.802632
6        F1 Score  0.866297
7             AUC  0.877005
8  mean abs error  0.121671

In [207]:
model_columns.transpose().reset_index().rename(columns={'index':'ANN'})

,ANN,0,1,2,3,4,5,6,7,8
0,measures,Train Accuracy,Train loss,Test Accuracy,Test loss,Precision,Recall,F1 Score,AUC,mean abs error
1,values,0.881034,0.290853,0.878329,0.298178,0.940933,0.802632,0.866297,0.877005,0.121671

#**Over Sampling with SMOTETomek**

In [4]:
df.head(5)

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,0,-1.422409,0,0,1,-0.366034,-0.460504,0,0,12,5,0,1,4,-0.142328,0,0,0
1,0,-0.653422,0,0,0,-0.366034,-0.460504,0,0,11,5,0,0,2,-1.033281,0,0,1
2,0,0.822955,1,0,0,4.347674,-0.460504,1,0,12,5,2,0,2,1.639578,1,0,0
3,0,-0.208323,0,0,0,-0.366034,-0.460504,0,0,12,5,1,0,1,-1.924234,0,1,0
4,0,2.621233,0,0,0,-0.366034,-0.460504,1,1,9,5,0,1,2,2.530531,0,0,0

In [11]:
df1=df.copy()
#Target
y=df1['HeartDisease']
#Features

X=df1.copy()
X=df1.drop('HeartDisease', axis=1)

In [ ]:
!pip install imblearn
from imblearn.combine import SMOTETomek
sm = SMOTETomek(random_state=42)

In [13]:
X_sm, y_sm = sm.fit_resample(X,y)

In [14]:
from sklearn.model_selection import train_test_split
X_sm_train, X_sm_test, y_sm_train, y_sm_test=train_test_split(X_sm,y_sm, test_size=0.3, random_state=42)
print(X_sm.shape)
print(y_sm.shape)

(418800, 17)
(418800,)

**ANN Model Prepare**

In [17]:
#to add 1st hidden layer
ml10 = Sequential()
ml10.add(Dense(6,activation = 'relu', input_dim = 17)) #no of feature 17
#to add 2nd hidden layer
ml10.add(Dense(6, activation = 'relu'))
#add output layer as target is in binary formate and reqire 1 neuron
ml10.add(Dense(1, activation = 'sigmoid'))
#compile
ml10.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [18]:
ml10.fit(X_sm_train, y_sm_train, batch_size = 10, epochs = 50)

Epoch 1/50
29316/29316 [==============================] - 66s 2ms/step - loss: 0.5146 - accuracy: 0.7530
Epoch 2/50
29316/29316 [==============================] - 48s 2ms/step - loss: 0.5049 - accuracy: 0.7574
Epoch 3/50
29316/29316 [==============================] - 49s 2ms/step - loss: 0.5037 - accuracy: 0.7582
Epoch 4/50
29316/29316 [==============================] - 52s 2ms/step - loss: 0.5027 - accuracy: 0.7589
Epoch 5/50
29316/29316 [==============================] - 48s 2ms/step - loss: 0.5024 - accuracy: 0.7587
Epoch 6/50
29316/29316 [==============================] - 51s 2ms/step - loss: 0.5021 - accuracy: 0.7594
Epoch 7/50
29316/29316 [==============================] - 49s 2ms/step - loss: 0.5019 - accuracy: 0.7592
Epoch 8/50
29316/29316 [==============================] - 47s 2ms/step - loss: 0.5018 - accuracy: 0.7591
Epoch 9/50
29316/29316 [==============================] - 47s 2ms/step - loss: 0.5015 - accuracy: 0.7591
Epoch 10/50
29316/29316 [==============================] - 47s 2ms/step - loss: 0.5012 - accuracy: 0.7599
Epoch 11/50
29316/29316 [==============================] - 48s 2ms/step - loss: 0.5010 - accuracy: 0.7600
Epoch 12/50
29316/29316 [==============================] - 47s 2ms/step - loss: 0.5008 - accuracy: 0.7602
Epoch 13/50
29316/29316 [==============================] - 46s 2ms/step - loss: 0.5006 - accuracy: 0.7607
Epoch 14/50
29316/29316 [==============================] - 47s 2ms/step - loss: 0.5006 - accuracy: 0.7603
Epoch 15/50
29316/29316 [==============================] - 46s 2ms/step - loss: 0.5005 - accuracy: 0.7606
Epoch 16/50
29316/29316 [==============================] - 46s 2ms/step - loss: 0.5003 - accuracy: 0.7607
Epoch 17/50
29316/29316 [==============================] - 48s 2ms/step - loss: 0.5001 - accuracy: 0.7609
Epoch 18/50
29316/29316 [==============================] - 46s 2ms/step - loss: 0.5001 - accuracy: 0.7606
Epoch 19/50
29316/29316 [==============================] - 45s 2ms/step - loss: 0.5000 - accuracy: 0.7613
Epoch 20/50
29316/29316 [==============================] - 46s 2ms/step - loss: 0.5000 - accuracy: 0.7611
Epoch 21/50
29316/29316 [==============================] - 47s 2ms/step - loss: 0.4998 - accuracy: 0.7608
Epoch 22/50
29316/29316 [==============================] - 47s 2ms/step - loss: 0.4998 - accuracy: 0.7609
Epoch 23/50
29316/29316 [==============================] - 54s 2ms/step - loss: 0.4997 - accuracy: 0.7615
Epoch 24/50
29316/29316 [==============================] - 51s 2ms/step - loss: 0.4996 - accuracy: 0.7612
Epoch 25/50
29316/29316 [==============================] - 48s 2ms/step - loss: 0.4995 - accuracy: 0.7611
Epoch 26/50
29316/29316 [==============================] - 51s 2ms/step - loss: 0.4996 - accuracy: 0.7610
Epoch 27/50
29316/29316 [==============================] - 48s 2ms/step - loss: 0.4997 - accuracy: 0.7614
Epoch 28/50
29316/29316 [==============================] - 49s 2ms/step - loss: 0.4996 - accuracy: 0.7617
Epoch 29/50
29316/29316 [==============================] - 48s 2ms/step - loss: 0.4995 - accuracy: 0.7607
Epoch 30/50
29316/29316 [==============================] - 47s 2ms/step - loss: 0.4996 - accuracy: 0.7616
Epoch 31/50
29316/29316 [==============================] - 46s 2ms/step - loss: 0.4995 - accuracy: 0.7614
Epoch 32/50
29316/29316 [==============================] - 45s 2ms/step - loss: 0.4996 - accuracy: 0.7616
Epoch 33/50
29316/29316 [==============================] - 45s 2ms/step - loss: 0.4995 - accuracy: 0.7619
Epoch 34/50
29316/29316 [==============================] - 45s 2ms/step - loss: 0.4995 - accuracy: 0.7612
Epoch 35/50
29316/29316 [==============================] - 47s 2ms/step - loss: 0.4994 - accuracy: 0.7614
Epoch 36/50
29316/29316 [==============================] - 47s 2ms/step - loss: 0.4994 - accuracy: 0.7612
Epoch 37/50
29316/29316 [==============================] - 47s 2ms/step - loss: 0.4994 - accuracy: 0.7614
Epoch 38/50
29316/29316 [==============================] - 46s 2ms/step - loss: 0.4995 - accuracy: 0.7614
Epoch 39/50
29316/29316 [==============================] - 46s 2ms/step - loss: 0.4994 - accuracy: 0.7612
Epoch 40/50
29316/29316 [==============================] - 49s 2ms/step - loss: 0.4994 - accuracy: 0.7613
Epoch 41/50
29316/29316 [==============================] - 46s 2ms/step - loss: 0.4994 - accuracy: 0.7616
Epoch 42/50
29316/29316 [==============================] - 46s 2ms/step - loss: 0.4993 - accuracy: 0.7619
Epoch 43/50
29316/29316 [==============================] - 47s 2ms/step - loss: 0.4995 - accuracy: 0.7613
Epoch 44/50
29316/29316 [==============================] - 47s 2ms/step - loss: 0.4993 - accuracy: 0.7615
Epoch 45/50
29316/29316 [==============================] - 48s 2ms/step - loss: 0.4993 - accuracy: 0.7611
Epoch 46/50
29316/29316 [==============================] - 48s 2ms/step - loss: 0.4994 - accuracy: 0.7615
Epoch 47/50
29316/29316 [==============================] - 49s 2ms/step - loss: 0.4993 - accuracy: 0.7614
Epoch 48/50
29316/29316 [==============================] - 48s 2ms/step - loss: 0.4992 - accuracy: 0.7617
Epoch 49/50
29316/29316 [==============================] - 49s 2ms/step - loss: 0.4992 - accuracy: 0.7619
Epoch 50/50
29316/29316 [==============================] - 48s 2ms/step - loss: 0.4993 - accuracy: 0.7614

In [19]:
 y_sm_pred=ml10.predict(X_sm_test)
 y_sm_pred[y_sm_pred <= 0.5] = 0
 y_sm_pred[y_sm_pred > 0.5] = 1

In [20]:
fp, tp, tn = roc_curve(y_sm_test, y_sm_pred)

Train_Accuracy_loss = ml10.evaluate(X_sm_train, y_sm_train)
Train_Accuracy = (Train_Accuracy_loss[1])
Train_loss = (Train_Accuracy_loss[0])

Test_Accuracy_loss =  ml10.evaluate(X_sm_test, y_sm_test)
Test_Accuracy = (Test_Accuracy_loss[1])
Test_loss = (Test_Accuracy_loss[0])

Precission = precision_score(y_sm_test, y_sm_pred)
Recall= recall_score(y_sm_test, y_sm_pred)
f1_Score=f1_score(y_sm_test, y_sm_pred)
AUC = auc(fp, tp)
mbe=mean_absolute_error(y_sm_test, y_sm_pred)
list_name = [["Train Accuracy", Train_Accuracy], ["Train loss", Train_loss], ["Test Accuracy", Test_Accuracy], ["Test loss", Test_loss],
             ["Precision",Precission], ["Recall", Recall],
             ['F1 Score',f1_Score], ["AUC", AUC],["mean abs error",mbe]]
results = pd.DataFrame (list_name, columns = ['measures', 'values'])
results

9162/9162 [==============================] - 12s 1ms/step - loss: 0.4989 - accuracy: 0.7618
3927/3927 [==============================] - 5s 1ms/step - loss: 0.4976 - accuracy: 0.7635

         measures    values
0  Train Accuracy  0.761840
1      Train loss  0.498876
2   Test Accuracy  0.763483
3       Test loss  0.497580
4       Precision  0.747705
5          Recall  0.793256
6        F1 Score  0.769808
7             AUC  0.763569
8  mean abs error  0.236517

In [21]:
results.transpose().reset_index().rename(columns={'index':'ANN'})

,ANN,0,1,2,3,4,5,6,7,8
0,measures,Train Accuracy,Train loss,Test Accuracy,Test loss,Precision,Recall,F1 Score,AUC,mean abs error
1,values,0.76184,0.498876,0.763483,0.49758,0.747705,0.793256,0.769808,0.763569,0.236517